code/AntonioCanalizador/AntonioCanalizador/Controllers/MyProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Mvc;
using AntonioCanalizador.Data;

namespace AntonioCanalizador.Controllers
{
    public class MyProfileController : Controller
    {

        DataContext db = new DataContext();

        [System.Web.Mvc.Authorize]
        public ActionResult Index()
        {
            if (!Request.IsAuthenticated || User.Identity.Name == "admin")
            {
                return RedirectToAction("Index", "Home");
            }

            int userid = Convert.ToInt32(User.Identity.Name);

            var cliente = (from c in db.Clientes
                           where c.nif_cliente == userid
                           select c).First();
            return View(cliente);
        }

        public ActionResult VerAgendados()
        {
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                int userid = Convert.ToInt32(User.Identity.Name);

                var faturas = (from f in db.Faturas
                               where f.nif_cliente == userid
                               where f.hora_inicio == null
                               orderby f.dia
                               select f).ToList();
                
                return View(faturas);
            }
        }
        public ActionResult Historico()
        {
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                int userid = Convert.ToInt32(User.Identity.Name);

                var faturas = (from f in db.Faturas
                               where f.nif_cliente == userid
                               where f.hora_inicio != null
                               orderby f.dia descending
                               select f).ToList();
                return View(faturas);
            }
        }

        public ActionResult Detalhes(int id)
        {
            var fatura = (from f in db.Faturas
                           where f.id_fatura == id
                           select f).First();
            return View(fatura);
        }

        public ActionResult Comentar(string comentario, int estrelas, int id_fatura)
        {
            var fat = (from f in db.Faturas
                       where f.id_fatura == id_fatura
                       select f).First();

            fat.comentarios = comentario;
            fat.estrelas = estrelas;
            db.SaveChanges();

            return RedirectToAction("Detalhes", new { id = id_fatura});
        }

        // GET api/<controller>
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET api/<controller>/5
        public string Get(int id)
        {
            return "value";
        }

        // POST api/<controller>
        public void Post([FromBody]string value)
        {
        }

        // PUT api/<controller>/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE api/<controller>/5
        public void Delete(int id)
        {
        }
    }
}

code/AntonioCanalizador/AntonioCanalizador/Views/Shared/_Layout.cshtml
@using AntonioCanalizador.Helpers;

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href=("~/Content/StyleSheet1.css") rel="stylesheet" type="text/css" />
    <link rel="shortcut icon" type="image/png" href="~/images/favicon.png">
</head>
<body>
    <div class="wrapper">
        <header>
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-brand">
                    <div class="collapse navbar-collapse" id="navbarCollapse">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item active">
                                <a class="nav-link" href='@Url.Action("About", "Home")'>Acerca</a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" href='@Url.Action("Contact", "Home")'>Contactos</a>
                            </li>
                        </ul>
                    </div>
                </div>
                @{
                    if (Utils.fBrowserIsMobile())
                    {
                        <a href='@Url.Action("Index", "Home")'>
                            <img src="~/images/administracao.png" style="position: absolute; height:63px; top:0; left:15%;" />
                        </a>
                    }
                    else
                    {
                        <a href='@Url.Action("Index", "Home")'>
                            <img src="~/images/logo.png" style="position: absolute; height:63px; top:0; left:15%;" />
                        </a>
                    }
                }

                <div style="position:absolute; right:15%;">
                    <a class="number">
                        <img src="~/images/number.png" style=" height:50px; top:0; " />
                    </a>
                    @{
                        if (Request.IsAuthenticated && User.Identity.Name == "admin")
                        {
                            <a href='@Url.Action("Home", "Admin")'>
                                <img src="~/images/administracao.png" style="margin-left:-5px; height:50px; top:0;" />
                            </a>
                        }
                        else
                        {
                            <a href='@Url.Action("Index", "Login")'>
                                <img src="~/images/login.png" style="margin-left:-5px; height:50px; top:0;" />
                            </a>
                        }
                    }

                </div>


            </nav>
        </header>
        <div class="content">
            <div class="container body-content">
                @RenderBody()
            </div>
        </div>


        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </div>
    <footer class="card-footer">
        <div class="firstrow" style="margin-left: 15%; width: 80%;">
            <div class="col-lg-8">
                <h3><span class="title" style="color:#EEEEEE; font-family:'San Francisco'; font-size:1.8vh;">&copy; @DateTime.Now.Year - António Canalizador. Todos os direitos reservados.</span></h3>
                <a href='@Url.Action("Contact", "Home")'><span class="title" style="color:#BBBFCA; font-family:'San Francisco'; font-size:1.8vh;">Contactos</span></a>
                <a><span class="title" style="color:#EEEEEE; font-family:'San Francisco'; font-size:1.5vh;"> • </span></a>
                <a href='@Url.Action("About", "Home")'><span class="title" style="color:#BBBFCA; font-family:'San Francisco'; font-size:1.8vh;">Acerca de nós</span></a>
                @{
                    if (Request.IsAuthenticated && User.Identity.Name == "admin")
                    {
                        <a><span class="title" style="color:#EEEEEE; font-family:'San Francisco'; font-size:1.5vh;"> • </span></a>
                        <a href='@Url.Action("Home", "Admin")'><span class="title" style="color:#BBBFCA; font-family:'San Francisco'; font-size:1.8vh;">Administração</span></a>
                    }
                    else
                    {
                        <a><span class="title" style="color:#EEEEEE; font-family:'San Francisco'; font-size:1.5vh;"> • </span></a>
                        <a href='@Url.Action("Login", "Admin")'><span class="title" style="color:#BBBFCA; font-family:'San Francisco'; font-size:1.8vh;">Login administração</span></a>
                    }
                }
            </div>
            <div class="col-lg-3">
                <a href="https://www.facebook.com/antoniocanalizador" target="_blank"><img src="~/images/facebook.png" style="height:50px; top:0; margin-left:10px;" /></a>
                <a href="https://www.instagram.com/antoniocanalizador" target="_blank"><img src="~/images/instagram.png" style="height:50px; top:0; margin-left:10px;" /></a>
                <a href="https://www.twitter.com/antoniocanalizador" target="_blank"><img src="~/images/twitter.png" style="height:50px; top:0; margin-left:10px;" /></a>
            </div>
        </div>
    </footer>
</body>


</html>

code/AntonioCanalizador/AntonioCanalizador/Views/Shared/_LayoutAuth.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @using AntonioCanalizador.Data;


<link href=("~/Content/StyleSheet1.css") rel="stylesheet" type="text/css" />
    <link rel="shortcut icon" type="image/png" href="~/images/favicon.png">
</head>
<body>
    <div class="wrapper">
        <header>
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-brand">
                    <div class="collapse navbar-collapse" id="navbarCollapse">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item active">
                                <a class="nav-link" href='@Url.Action("About", "Home")'>Acerca</a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" href='@Url.Action("Contact", "Home")'>Contactos</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <a href='@Url.Action("Home", "Home")'>
                    <img src="~/images/logo.png" style="position: absolute; height:63px; top:0; left:15%;" />
                </a>
                <div style="position:absolute; right:15%;">
                    <a class="number">
                        <img src="~/images/number.png" style=" height:50px; top:0; " />
                    </a>
                    @{
                        if (Request.IsAuthenticated)
                        {
                            int userid = Convert.ToInt32(User.Identity.Name);

                            DataContext db = new DataContext();
                            var cliente = (from c in db.Clientes
                                           where c.nif_cliente == userid
                                           select c).First();

                            <a href='@Url.Action("Index", "MyProfile")'>
                                <img src='@cliente.foto' class="rounded-circle-profile" style="margin-left:2px; margin-top:5px; top:0; position:absolute;" />
                            </a>
                            }

                        }

                        <a href='@Url.Action("Index", "MyProfile")'>
                            <img src="~/images/areacliente.png" style="margin-left:-5px; height:50px; top:0;" />
                        </a>
                    </div>


            </nav>
        </header>
        <div class="content">
            <div class="container body-content">
                @RenderBody()
            </div>
        </div>


        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </div>
    <footer class="card-footer">
        <div class="firstrow" style="margin-left: 15%; width: 80%;">
            <div class="col-lg-9">
                <h3><span class="title" style="color:#EEEEEE; font-family:'San Francisco'; font-size:1.8vh;">&copy; @DateTime.Now.Year - António Canalizador. Todos os direitos reservados.</span></h3>
                <a href='@Url.Action("Contact", "Home")'><span class="title" style="color:#BBBFCA; font-family:'San Francisco'; font-size:1.8vh;">Contactos</span></a>
                <a><span class="title" style="color:#EEEEEE; font-family:'San Francisco'; font-size:1.5vh;"> • </span></a>
                <a href='@Url.Action("About", "Home")'><span class="title" style="color:#BBBFCA; font-family:'San Francisco'; font-size:1.8vh;">Acerca de nós</span></a>
            </div>
            <div class="col-lg-3">
                <a href="https://www.facebook.com/antoniocanalizador" target="_blank"><img src="~/images/facebook.png" style="height:50px; top:0; margin-left:10px;" /></a>
                <a href="https://www.instagram.com/antoniocanalizador" target="_blank"><img src="~/images/instagram.png" style="height:50px; top:0; margin-left:10px;" /></a>
                <a href="https://www.twitter.com/antoniocanalizador" target="_blank"><img src="~/images/twitter.png" style="height:50px; top:0; margin-left:10px;" /></a>
            </div>
        </div>
    </footer>
</body>


</html>