code/AntonioCanalizador/AntonioCanalizador/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AntonioCanalizador.Data;
using AntonioCanalizador.Helpers;

namespace AntonioCanalizador.Controllers
{

    public class HomeController : Controller
    {
        DataContext db = new DataContext();

        public ActionResult Index()
        {
            if (Utils.fBrowserIsMobile())
            {
                return RedirectToAction("IndexToday", "Mobile");
            }

            if (Request.IsAuthenticated && User.Identity.Name!="admin")
            {
                return RedirectToAction("Home", "Home");
            }
            var des = (from c in db.Servicoes where c.id_tipo == 1 select c.nome).ToList();
            var por = (from c in db.Servicoes where c.id_tipo == 2 select c.nome).ToList();
            var can = (from c in db.Servicoes where c.id_tipo == 3 select c.nome).ToList();
            var fur = (from c in db.Servicoes where c.id_tipo == 4 select c.nome).ToList();

            ViewData["desentupimentos"] = des;
            ViewData["portas"] = por;
            ViewData["canalizacao"] = can;
            ViewData["furosdagua"] = fur;
            return View();
        }

        public ActionResult Home()
        {
            if (Utils.fBrowserIsMobile())
            {
                return RedirectToAction("IndexToday", "Mobile");
            }

            if (!Request.IsAuthenticated || User.Identity.Name=="admin")
            {
                return RedirectToAction("Index", "Home");
            }
            var des = (from c in db.Servicoes where c.id_tipo == 1 select c.nome).ToList();
            var por = (from c in db.Servicoes where c.id_tipo == 2 select c.nome).ToList();
            var can = (from c in db.Servicoes where c.id_tipo == 3 select c.nome).ToList();
            var fur = (from c in db.Servicoes where c.id_tipo == 4 select c.nome).ToList();

            ViewData["desentupimentos"] = des;
            ViewData["portas"] = por;
            ViewData["canalizacao"] = can;
            ViewData["furosdagua"] = fur;
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Maintenance()
        {
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

code/AntonioCanalizador/AntonioCanalizador/Controllers/ServicosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Security.Cryptography;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;
using AntonioCanalizador.Data;
using AntonioCanalizador.Models;
using AntonioCanalizador.Helpers;
using System.Net.Mail;

namespace AntonioCanalizador.Controllers
{
    public class ServicosController : Controller
    {
        DataContext db = new DataContext();


        [System.Web.Mvc.Authorize]
        public ActionResult Agendar(string servico, int erro)
        {
            Servico serv = (from s in db.Servicoes where s.nome == servico select s).First();
            Agendar ag = new Agendar();
            ag.servico = serv;
            ag.error = erro;
            return View(ag);
        }

        [System.Web.Mvc.HttpPost]
        public ActionResult Confirmar(DateTime date, string time, string nome)
        {
            int error_id = 42;
            var h = new string(time.TakeWhile(char.IsDigit).ToArray());
            int hora = Convert.ToInt32(h);
            int userid = Convert.ToInt32(User.Identity.Name);

            if (date < DateTime.Today) error_id = 1;
            else if (date == DateTime.Today && hora <= DateTime.Now.Hour) error_id = 2;
            else
            {
                var funcs = (from func in db.Funcionarios
                             select func).ToList();

                int turno = 0;
                if (hora >= 9 && hora < 17) turno = 1;
                else if (hora >= 17 && hora < 23) turno = 2;
                else if (hora > 0 && hora < 1) turno = 2;
                else if (hora >= 1 && hora < 9) turno = 3;

                var servico = (from s in db.Servicoes
                               where s.nome == nome
                               select s).First();

                for (var i = 0; i < funcs.Count(); i++)
                {
                    var idfunc = funcs[i].id_funcionario;
                    var agenda = (from f in db.Faturas
                                  join s in db.Servicoes
                                  on f.id_servico equals s.id_servico
                                  where ((f.hora <= hora && f.hora + s.duracaoprevista > hora) || (hora+servico.duracaoprevista>f.hora))
                                  where f.dia == date
                                  where f.preco_total==null
                                  where f.id_funcionario == idfunc
                                  select f).Any();

                    if (agenda || funcs[i].turno != turno) { funcs.RemoveAt(i); i--; }
                }

                if (funcs.Count()==0) error_id = 3;
                else
                {
                    

                    var cliente = (from c in db.Clientes
                                   where c.nif_cliente == userid
                                   select c).First();

                    Fatura fatura = new Fatura();
                    fatura.id_servico = servico.id_servico;
                    fatura.nome_servico = servico.nome;
                    fatura.id_funcionario = funcs.First().id_funcionario;
                    fatura.nome_funcionario = funcs.First().nome;
                    fatura.nif_cliente = cliente.nif_cliente;
                    fatura.nome_cliente = cliente.nome;
                    fatura.rua_cliente = cliente.rua;
                    fatura.andar_cliente = cliente.andar;
                    fatura.porta_cliente = cliente.porta;
                    fatura.localidade_cliente = cliente.localidade;
                    fatura.cod_postal_cliente = cliente.cod_postal;
                    fatura.dia = date;
                    fatura.hora = hora;
                    fatura.hora_inicio = null;
                    fatura.hora_fim = null;
                    fatura.preco_materiais = 0;
                    fatura.preco_total = 0;
                    fatura.preco_trabalho = 0;
                    fatura.ref_pagamento = 0;
                    fatura.ocorrencias = "";
                    fatura.estrelas = 0;
                    fatura.comentarios = "";

                    enviarEmailSMS(cliente.email, cliente.telemovel, fatura.dia.ToString("d MMM"), fatura.hora, fatura.nome_servico);
                    db.Faturas.Add(fatura);
                    db.SaveChanges();


                }
            }
            return RedirectToAction("Agendar", new { servico = nome , erro = error_id});
        }

        static void enviarEmailSMS(string email, int telemovel, string dia, int hora, string servico)
        {
            
            // INITIATE SMTP
            SmtpClient smtp = new SmtpClient("smtp.gmail.com", 587);
            smtp.UseDefaultCredentials = false;
            smtp.EnableSsl = true;
            smtp.Credentials = new System.Net.NetworkCredential("dynamite0697@gmail.com", "BersekerBarrage314#");
            //smtp.Credentials = new System.Net.NetworkCredential("geral.antonio.canalizador@gmail.com", "AntonioCanalizador97#");


            // MESSAGE EMAIL
            MailMessage message = new MailMessage();
            message.To.Add(email);
            message.From = new MailAddress("dynamite0697@gmail.com", "António Canalizador");
            //message.From = new MailAddress("geral.antonio.canalizador@gmail.com", "António Canalizador");
            message.Subject = "Serviço agendado";
            message.Body = string.Concat("O seu serviço de ", servico, " foi agendado com sucesso para o dia ", dia, " às ", hora,"h. Obrigado.");

            smtp.Send(message);

            // MESSAGE SMS
            MailMessage message2 = new MailMessage(); ;
            message2.To.Add(string.Concat(telemovel,"@txtlocal.co.uk"));
            message2.From = new MailAddress("dynamite0697@gmail.com", "António Canalizador");
            //message2.From = new MailAddress("geral.antonio.canalizador@gmail.com", "António Canalizador");
            message2.Subject = "Serviço agendado";
            message2.Body = string.Concat("O seu servico de ", servico, " foi agendado com sucesso para o dia ", dia, " as ", hora, "h. Obrigado.");

            smtp.Send(message2);
       
        }

    }
}

code/AntonioCanalizador/AntonioCanalizador/Views/Home/About.cshtml
@{
    ViewBag.Title = "Acerca de nós";
}
@{
    if (Request.IsAuthenticated && User.Identity.Name != "admin")
    {
        Layout = "~/Views/Shared/_LayoutAuth.cshtml";
    }
    else
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }

}



<div>
    <div style="width:100%; margin-top: 50px; background-color: #293C4A;">
        <div class="lineseparator">ACERCA DE NÓS </div>
        <div style="width:99%; padding-left:15.5%; text-align:left; background-color: #293C4A;">
            <h6><a><span class="text-small" style="color:#293C4A; font-size:0px;">. </span></a></h6>
            <div class="firstrow">
                <div class="col-lg-3">
                    <h3><span class="title_left">A nossa história</span></h3>
                    <h6><a><span class="text-small" style="font-size:2vh;">
                        Fundada em 1938 pelo prestigiado Sr. António Tomás Taveira Santos, grande benemérito da vila.
                        Iniciou-se assim com a prestação de serviços de venda de água porta a porta, um trabalho modesto,
                        mas honrado e muito importante para a higiene e saneamento da população.</span></a></h6>
                    <h6><a><span class="text-small" style="font-size:2vh;">
                        Ao longo dos anos e com o aparecimento das canalizações na casa das pessoas, o nosso serviço foi-se
                        adaptando às necessidades dos nossos clientes, permitindo um crescimento da nossa empresa e também
                        a familiaridade entre os nossos técnicos e os clientes.</span></a></h6>
                    <h6><a><span class="text-small" style="font-size:2vh;">
                        Este negócio foi passado de geração em geração, herdando sempre os ensinamentos dos antepassados.
                        Isso é o que nos distingue e o que faz com que prestemos o melhor serviço da região, pois os nossos
                        laços familiares estendem-se a todos os nossos clientes.</span></a></h6>
                </div>
                <div class="col-lg-3" style="margin-left:50px;">
                    <h3><span class="title_left">Os nossos serviços</span></h3>
                    <h6><a><span class="text-small" style="font-size:2vh;">
                        Atualmente contamos com uma vasta gama de serviços ao seu dispor, sendo que a nossa oferta cresce
                        continuamente, tal como os equipamentos que temos ao seu dispor.</span></a></h6>
                    <h6><a><span class="text-small" style="font-size:2vh;">
                        A qualidade do serviço é que nunca muda. Sempre a melhor prestação, com a familiaridade e preços
                        baixos que o habituamos.</span></a></h6>
                    <h6><a><span class="text-small" style="font-size:2vh;">
                        Se precisa de algum produto, não hesite também em passar pela nossa loja. Temos todos os produtos
                        de qualidade e aos preços mais baixos.</span></a></h6>
                </div>
                <div class="col-lg-3" style="margin-left:50px;">
                    <h3><span class="title_left">Página Online</span></h3>
                    <h6><a><span class="text-small" style="font-size:2vh;">
                        Seja bem-vindo/a ao nosso novo website. Concebido com um design moderno e de fácil utilização, tornando
                        fácil para si agendar os nossos serviços em qualquer lado e a qualquer hora.</span></a></h6>
                    <h6><a><span class="text-small" style="font-size:2vh;">
                        Aqui poderá criar a sua conta pessoal e agendar qualquer serviço que pretenda para a sua data e hora de
                        preferência. Acabaram as chamadas telefónicas e o tempo de espera. Com este novo serviço, o seu agendamento
                        é rápido e o horário estabelecido é cumprido!</span></a></h6>
                    <h6><a><span class="text-small" style="font-size:2vh;">Para além disto, pode verificar na sua área pessoal,
                        quais os serviços que tem agendados e o seu histórico, podendo também efetuar uma avaliação ao serviço
                        prestado pelos nossos técnicos. Usufrua de inúmeras vantagens.
                        </span></a></h6>
                </div>
            </div>
        </div>
    </div>
</div>

code/AntonioCanalizador/AntonioCanalizador/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contactos";

    if (Request.IsAuthenticated && User.Identity.Name!="admin")
    {
        Layout = "~/Views/Shared/_LayoutAuth.cshtml";
    }
    else
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }

}

<div>
    <div style="width:100%; margin-top: 50px; background-color: #293C4A;">
        <div class="lineseparator">CONTACTOS </div>
        <div style="width:99%; padding-left:15.5%; text-align:left; background-color: #293C4A;">
            <h6><a><span class="text-small" style="color:#293C4A; font-size:0px;">. </span></a></h6>
            <div class="firstrow">
                <div class="col-lg-3">
                    <h3><span class="title_left">Localização</span></h3>
                    <h6><a><span class="text-small" style="font-size:2vh;">R. Eng. Vilalobos, 10 </span></a></h6>
                    <h6><a><span class="text-small" style="font-size:2vh;">4715-282 - Lamaçães, Braga </span></a></h6>
                </div>
                <div class="col-lg-3" style="margin-left:50px;">
                    <h3><span class="title_left">Telefone</span></h3>
                    <h6><a><span class="text-small" style="font-size:2vh;">Linha SOS: 252 202 303 </span></a></h6>
                    <h6><a><span class="text-small" style="font-size:2vh;">Geral: 252 121 833 </span></a></h6>
                </div>
                <div class="col-lg-3" style="margin-left:50px;">
                    <h3><span class="title_left">Email</span></h3>
                    <h6><a href="mailto:geral@antoniocanalizador.pt"><span class="text-small" style="font-size:2vh;">geral@antoniocanalizador.pt</span></a></h6>
                </div>
            </div>
        </div>
    </div>
</div>

code/AntonioCanalizador/AntonioCanalizador/Views/Home/Home.cshtml
@{
    Layout = "~/Views/Shared/_LayoutAuth.cshtml";
}
@{
    ViewBag.Title = "António Canalizador";
}

<div>
    <div id="myCarousel" class="carousel" data-ride="carousel">
        <div class="carousel-inner">
            <div class="item active">
                <img src="~/images/banner.png" style="width:100%;">
                <div class="containerheader">
                    <div class="carousel-caption text-left">
                        <p><span class="titleheader" style="font-size:2vw;">A equipa da António Canalizador está preparada para atender qualquer emergência na sua casa, a qualquer hora do dia!</span></p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="lineseparator">OS NOSSOS SERVIÇOS</div>

    <div style="width: 100%; background-color: #293C4A;">
        <div style="width: 90%; background-color: #293C4A;">
            <div class="firstrow" style="padding-left: 17%; padding-right:5%">
                <div class="col-lg-3">
                    <img class="rounded-circle" src="~/images/desentupimentos.png" alt="Generic placeholder image" width="100" height="100">
                    <h2><span class="title" style="color:#E69335;">DESENTUPIMENTOS</span></h2>
                    @foreach (var std in (List<string>)ViewData["desentupimentos"])
                    {
                        <p><a href='@Url.Action("Agendar", "Servicos", new {servico=std, erro=0})'><span class="text-small"> > @std </span></a></p>

                    }
                </div>
                <div class="col-lg-3">
                    <img class="rounded-circle" src="~/images/portas.png" alt="Generic placeholder image" width="100" height="100">
                    <h2><span class="title" style="color:#E69335;">PORTAS E FECHADURAS</span></h2>
                    @foreach (var std in (List<string>)ViewData["portas"])
                    {
                        <p><a href='@Url.Action("Agendar", "Servicos", new {servico=std, erro=0})'><span class="text-small"> > @std </span></a></p>
                    }
                </div>
                <div class="col-lg-3">
                    <img class="rounded-circle" src="~/images/canalizacao.png" alt="Generic placeholder image" width="100" height="100">
                    <h2><span class="title" style="color:#E69335;">CANALIZAÇÃO</span></h2>
                    @foreach (var std in (List<string>)ViewData["canalizacao"])
                    {
                        <p><a href='@Url.Action("Agendar", "Servicos", new {servico=std, erro=0})'><span class="text-small"> > @std </span></a></p>
                    }
                </div>
                <div class="col-lg-3">
                    <img class="rounded-circle" src="~/images/furos.png" alt="Generic placeholder image" width="100" height="100">
                    <h2><span class="title" style="color:#E69335;">FUROS DE ÁGUA</span></h2>
                    @foreach (var std in (List<string>)ViewData["furosdagua"])
                    {
                        <p><a href='@Url.Action("Agendar", "Servicos", new {servico=std, erro=0})'><span class="text-small"> > @std </span></a></p>
                    }
                </div>
            </div>
        </div>
    </div>
    <div style="width: 100%; background-color: #f2f4f9;">
        <div class="lineseparator">PORQUÊ NÓS</div>

        <div class="row featurette" style="width:99%;">
            <div class="col-md-5" style="margin-left:15.4%; margin-top:40px;">

                <p><span class="text-normal">> Serviço confiável e recomendado desde 1938.</span></p>
                <p><span class="text-normal">> Disponível 24 horas por dia, 7 dias por semana, 365 dias por ano.</span></p>
                <p><span class="text-normal">> Técnicos mais experientes da zona.</span></p>
                <p><span class="text-normal">> Serviço rápido e limpo.</span></p>
                <p><span class="text-normal">> Possibilidade de efetuar agendamento online.</span></p>
            </div>
            <div class="col-md-5">
                <img src="~/images/ribbons.png" style="width:65%; margin-top:70px;">
            </div>
        </div>
    </div>
</div>

code/AntonioCanalizador/AntonioCanalizador/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    ViewBag.Title = "António Canalizador";
}

<div>
    <div id="myCarousel" class="carousel" data-ride="carousel">
        <div class="carousel-inner">
            <div class="item active">
                <img src="~/images/banner.png" style="width:100%;">
                <div class="containerheader">
                    <div class="carousel-caption text-left">
                        <p><span class="titleheader" font-size="2vw">A equipa da António Canalizador está preparada para atender qualquer emergência na sua casa, a qualquer hora do dia!</span></p>
                        <p><a class="btn btn-lg btn-primary" href='@Url.Action("Index", "Login")' role="button">Registe-se já!</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="lineseparator">OS NOSSOS SERVIÇOS</div>

    <div style="width: 100%; background-color: #293C4A;">
        <div style="width: 90%; background-color: #293C4A;">
            <div class="firstrow" style="padding-left: 17%; padding-right:5%">
                <div class="col-lg-3">
                    <img class="rounded-circle" src="~/images/desentupimentos.png" alt="Generic placeholder image" width="100" height="100">
                    <h2><span class="title" style="color:#E69335;">DESENTUPIMENTOS</span></h2>
                    @foreach(var std in (List<string>)ViewData["desentupimentos"])
                    {
                        <p><a><span class="text-small"> > @std </span></a></p>
                    }
                </div>
                <div class="col-lg-3">
                    <img class="rounded-circle" src="~/images/portas.png" alt="Generic placeholder image" width="100" height="100">
                    <h2><span class="title" style="color:#E69335;">PORTAS E FECHADURAS</span></h2>
                    @foreach (var std in (List<string>)ViewData["portas"])
                    {
                        <p><a><span class="text-small"> > @std </span></a></p>
                    }
                </div>
                <div class="col-lg-3">
                    <img class="rounded-circle" src="~/images/canalizacao.png" alt="Generic placeholder image" width="100" height="100">
                    <h2><span class="title" style="color:#E69335;">CANALIZAÇÃO</span></h2>
                    @foreach (var std in (List<string>)ViewData["canalizacao"])
                    {
                        <p><a><span class="text-small"> > @std </span></a></p>
                    }
                </div>
                <div class="col-lg-3">
                    <img class="rounded-circle" src="~/images/furos.png" alt="Generic placeholder image" width="100" height="100">
                    <h2><span class="title" style="color:#E69335;">FUROS DE ÁGUA</span></h2>
                    @foreach (var std in (List<string>)ViewData["furosdagua"])
                    {
                        <p><a><span class="text-small"> > @std </span></a></p>
                    }
                </div>
            </div>
        </div>
    </div>
    <div style="width: 100%; background-color: #f2f4f9;">
        <div class="lineseparator">PORQUÊ NÓS</div>

        <div class="row featurette" style="width:99%;">
            <div class="col-md-5" style="margin-left:15.4%; margin-top:40px;">

                <p><span class="text-normal">> Serviço confiável e recomendado desde 1938.</span></p>
                <p><span class="text-normal">> Disponível 24 horas por dia, 7 dias por semana, 365 dias por ano.</span></p>
                <p><span class="text-normal">> Técnicos mais experientes da zona.</span></p>
                <p><span class="text-normal">> Serviço rápido e limpo.</span></p>
                <p><span class="text-normal">> Possibilidade de efetuar agendamento online.</span></p>
            </div>
            <div class="col-md-5">
                <img src="~/images/ribbons.png" style="width:65%; margin-top:70px;">
                <p><a class="btn btn-lg btn-primary" style="margin-top:50px;"  href='@Url.Action("Index", "Login")' role="button">Registe-se já!</a></p>
            </div>
        </div>
    </div>
</div>

code/AntonioCanalizador/AntonioCanalizador/Views/Home/Maintenance.cshtml
@{
    Layout = "~/Views/Shared/_LayoutAuth.cshtml";
}



<body style="background-color:#ffffff;">
    <div style="text-align:center; width:100%; padding-bottom: 80.5px;">
        <img src="https://cdn.dribbble.com/users/49067/screenshots/3710403/maintenance-panel800600.gif" draggable="false" style="width:40%; height:auto;" />
        <h3><span class="title" style="color:#293C4A; font-size:5vh;">PÁGINA SOB MANUTENÇÃO</span></h3>
        <h3><span class="title" style="color:#293C4A; font-family:'San Francisco'; font-size:2.6vh;">Estamos a adicionar novas funcionalidades ao seu website. Por favor volte mais tarde. :)</span></h3>
    </div>
</body>